version: "3.8"
services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./backend/data:/data  
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env.sample
    ports:
      - "5000:5000"
    depends_on:
         - mongodb
 frontend:
     container_name: frontend
     build: ./frontend
     env_file:
       - ./backend/.env.sample
     ports:
       - "5173:5173"

volumes:
  data:
CLOUDINARY_CLOUD_NAME= dn6kdxafh
CLOUDINARY_KEY=954585835865629
CLOUDINARY_SECRET=ESAsBZbs7g_5XiTkO5C6Ncji3ik
MPBOX_TOKEN=sk.eyJ1IjoiaHlhcmVsZ2l0czEiLCJhIjoiY2x2bTY5MG9mMmhsbjJrbnZyM2MwYnF4NyJ9.EVH9EBXIocbiWIytnaIqgA
DB_URL=”mongodb+srv://hyarelgits:SCs32WRgn4PVGKDK@cluster0.5fcsrl8.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0”
NAME=hyarelgits
SECRETS=hyarelshack
